### ISSUE TITLE
Tomahawk crash with "std::regex_error" error

### ISSUE THREAD

**Issue by alanorth** [mklarqvist/Tomahawk#32]
I'm trying to use Tomahawk on CentOS 7. Compilation is successful, but the resulting binary crashes immediately after execution:

```
$ ./tomahawk
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
zsh: abort      ./tomahawk
```

I am *not* using the provided `install.sh` script, instead using the following library versions as provided by CentOS 7:

- libcurl-devel-7.29.0-57.el7.x86_64
- openssl-devel-1.0.2k-19.el7.x86_64
- htslib-devel-1.9-5.el7.x86_64
- libzstd-devel-1.4.4-1.el7.x86_64

I notice you're using a specific commit hash for htslib in `install.sh`. Does tomahawk depend on certain versions of any of these libraries? Thanks!

**Comment by jeremymcrae** [comment]
I had the same issue on CentOS 7. This seems to be a problem when using the default CentOS 7 compiler (gcc 4.8.5), which doesn't fully support regex in c++. Using a more recent compiler built a functional binary for me.

**Comment by alanorth** [comment]
@jeremymcrae you're right. I just tried it with GCC 7.3.1 from devtoolset-7 and now the Tomahawk binary runs. Cheers!
